Repository scientific-python/lazy-loader, pull requests merged in 2024-01, with the labels that each got.

#87 Update pre-commit
  .pre-commit-config.yaml
Labels: type: Maintenance

#83 Avoid exception when __frame_data["code_context"] is None
  lazy_loader/__init__.py
Labels: type: Bug fix

#48 ENH: Add require argument to load() to accept version specifiers
  README.md
  lazy_loader/__init__.py
  lazy_loader/tests/test_lazy_loader.py
  pyproject.toml
Labels: type: Enhancement

#90 Make `lazy_load.load` partially thread-safe
  lazy_loader/__init__.py
  lazy_loader/tests/import_np_parallel.py
  lazy_loader/tests/test_lazy_loader.py
Labels: type: Bug fix

#91 Add security contact
  SECURITY.md
Labels: type: Documentation
